nav:
  - name: "Inicio"
    url: "/"
    section: inicio
  - name: "Descargas"
    url: "/descargas"
    section: descargas
  - name: "Qui√©nes somos"
    url: "/quienes-somos"
    section: quienes
  - name: "FAQ"
    url: "/faq"
    section: faq
  - name: "Aviso de privacidad"
    url: "/politicas-privacidad"
    section: privacidad
  - name: "Contacto"
    url: "/contacto"
    section: contacto
